version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - pira_data:/var/lib/mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

volumes:
  pira_data:
